### ISSUE TITLE
翻譯的語意順暢問題

### ISSUE THREAD

**Issue by TMHINKH** [ljsabc/mangaEditor-frontend#27]
氣泡的OCR準確度很高
但是翻譯就有點文不達意，可以考慮翻譯直接連接GOOGLE翻譯進行翻譯會相對順暢些
或是保留渣翻跟GOOGLE翻譯兩種給使用者進行選擇

**Comment by ljsabc** [comment]
This problem has been reported for multiple times but I am afraid I cannot find the "best" way to solve it, as the translation API is ever-changing and every year different people come to me to suggest a new service API provider. 

渣翻 comes from either Azure translation, or Baidu, depending on the server connectability. They were reported to be good for the last 3 years and I believe they are okay for most of the general reading cases. 

I suggest you to experiment with more translation testings by:

1. Uploading one sample manga page;
2. Extract all texts through the functionality on the page;
3. Test the text with different service providers. 

I think this manual ways of solution may be more suitable for you, as you can always choose the best service based on your flavors. I will consider implement a selection of service providers, but the cost is a big issue and I cannot spend more than 10$ in this non-profit project. For now, the income from the ads is still not enough to cover the server processing powers. 

I will keep opening this issue until I decide if this will be a wontfix, or to implement the service selector myself.
