### ISSUE TITLE
Spacing ocidental words

### ISSUE THREAD

**Issue by igorquintaes** [ljsabc/mangaEditor-frontend#9]
All spaces are recognized as break lines. But, while writing, it displays correctly.

![image](https://user-images.githubusercontent.com/10831729/98037497-6ea0e600-1dfa-11eb-856f-de817c8c159d.png)

![image](https://user-images.githubusercontent.com/10831729/98037514-7496c700-1dfa-11eb-8a0c-0ee8303bcdab.png)

**Comment by ljsabc** [comment]
I reproduced this issue and confirm this is a bug. As I am a little bit busy now I guess I can fix by next maintenance window (maybe 2 weeks later).

**Comment by ljsabc** [comment]
@igorquintaes  I finally fix this in 835ded061f8825a077927f7f3f1f2926e6ad90db. 
It should work now.
